airflow: true
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
    jobAnnotations:
        "argocd.argoproj.io/hook": Sync
webserverSecretKey: "42af9cc2d6ea694be0c699f11e415ea2"