apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret
  namespace: airflow
type: Opaque
data:
  webserver-secret-key: MWIzZTUyNjEwYjNlYTM0MzZlMDFiMWE5N2YzYjhmY2M=  # base64 de "1b3e52610b3ea3436e01b1a97f3b8fcc"

---

apiVersion: v1
kind: Secret
metadata:
  name: airflow-ssh-secret
  namespace: airflow
type: Opaque
data:
  gitSshKey: LS0tLS1CRUdJTi...