createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
  jobAnnotations:
    "argocd.argoproj.io/hook": Sync

webserverSecretKey: "1b3e52610b3ea3436e01b1a97f3b8fcc"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
